### ISSUE TITLE
Feature request: only show Mac shortcuts in the list

### ISSUE THREAD

**Issue by AdeTheux** [lukdiekm/alfred-shortcuts#1]
Thanks for this cool workflow.
Since I have a million shortcuts for iPhone and only a few that can actually run on Mac, it would be nice, if at all possible, to only list in Alfred the ones that are part of the category "Mac", for example.

**Comment by lukdiekm** [comment]
Hi, 
please try release v0.3. It supports filtering for a given folder.

**Comment by AdeTheux** [comment]
I must be doing something incorrectly but now don't have any results anymore.
This is the folder:
<img width="184" alt="image" src="https://user-images.githubusercontent.com/1615367/139540575-d7b97b33-3bae-4d25-b55d-815128243d47.png">

And this is the config:
<img width="371" alt="image" src="https://user-images.githubusercontent.com/1615367/139540578-d9b5e54b-4d81-443d-8841-4d706da6fc36.png">

Thanks

**Comment by stefanotto** [comment]
@AdeTheux  `listShortcuts.sh` uses a wrong argument. Should be `--folder-name` instead of `--folder`.

**Comment by lukdiekm** [comment]
Sorry, my mistake. I will fix this soon.

**Comment by lukdiekm** [comment]
@AdeTheux please try v0.3.1

**Comment by owenfiscus** [comment]
Not OP but worked for me!
