### ISSUE TITLE
Configure keyword `sc` with space required

### ISSUE THREAD

**Issue by CourierKyn** [lukdiekm/alfred-shortcuts#2]
I'm new to Alfred workflows. But I found setting the switch `with space` on would be convenient. Because when you type `sc` and hit Enter, Alfred will autocomplete the missing space for you.

I set this for myself for now.

<img width="675" alt="image" src="https://user-images.githubusercontent.com/29699904/139558087-15aa6056-28e0-4488-ba14-e3bcd1173fb3.png">

**Comment by lukdiekm** [comment]
Not sure, but I think Alfreds default behaviour in this situation is the space. That's why I use it in the workflow. Users can change it the way you described, if they prefer hitting enter.
