### ISSUE TITLE
Getting an error when executing a shortcut

### ISSUE THREAD

**Issue by bergjs** [lukdiekm/alfred-shortcuts#4]
![image](https://user-images.githubusercontent.com/2174131/141500483-dd235870-1759-4e4b-92bb-c602f8a3c410.png)

I tried it with two different workflows that normally work fine. I couldn't find more information about the error unfortunately..

**Comment by lukdiekm** [comment]
Is your shortcut expecting any input? Can you share it?

**Comment by bergjs** [comment]
They have in common, that they are reading the contents of a folder. Here's the shortcut https://www.icloud.com/shortcuts/e4cd5ced933540d7bd3208904ee63f1e

**Comment by lukdiekm** [comment]
There are two (little) problems:
First you need to give the shortcut access to files. Open the settings of the shortcut -> privacy ("Datenschutz") and choose "ask before delete" ("Vor dem löschen nachfragen").

<img width="287" alt="Bildschirmfoto 2021-11-14 um 17 15 17" src="https://user-images.githubusercontent.com/10906513/141689074-353082b9-a8e5-4422-8342-cf1f2260412d.png">

Also there is a problem with letters like öäü. I'll see if i can fix that, but until then you can try renaming the shortcut.

**Comment by bergjs** [comment]
Removing the Umlaut did it for me! Thanks for your help and thanks for the workflow!

**Comment by lukdiekm** [comment]
hi @bergjs release v0.3.2 should be able to handle öäü

**Comment by bergjs** [comment]
Really nice, thanks for your work!
