### ISSUE TITLE
Adding the .alfredworkflow file for ease of sharing

### ISSUE THREAD

**Issue by thatcanadiangirl** [lukdiekm/alfred-shortcuts#5]
Hiya, Vero from the Alfred team here! I wondered if you might consider adding the .alfredworkflow file itself to your repository and linked from your readme? This would help make the workflow more approachable for community members. :)

**Comment by lukdiekm** [comment]
Hi Vero,

*.alfredworkflow files for each version can be found in the releases-section. I will add a link to the readme :)

Have a great day!

**Comment by thatcanadiangirl** [comment]
Fab, thanks for adding it so quick :) This will undoubtedly be helpful for folks discovering your workflow!
