### ISSUE TITLE
Can not run shortcut with Swedish characters "å" in the title

### ISSUE THREAD

**Issue by antee** [lukdiekm/alfred-shortcuts#8]
Hey! Thank you so much for this workflow! Works great in general, but found an issue with running shortcuts that have the Swedish character "å" in it. Would guess it is the same for å, ä, ö

This is the debug output:
```
[16:03:39.919] macOS Shortcuts[Script Filter] Processing complete
[16:03:39.922] macOS Shortcuts[Script Filter] Passing output 'Kontor På' to Run Script
[16:03:40.044] ERROR: macOS Shortcuts[Run Script] Error: The requested shortcut was not found
```

When listing the shortcuts before running it I see that the shortcut is listed and the characters render ok in the debug output. Reduced example:

`<?xml version="1.0" encoding="UTF-8"?><items><item uid="Kontor På" valid="YES" autocomplete="Kontor På"><title>Kontor På</title><subtitle>Kontor På</subtitle><icon>sc-icon.png</icon><arg>Kontor På</arg></item> ... </items>`

Changing the name of the shortcut to "Kontor pa" makes it work.

**Comment by lukdiekm** [comment]
Hi,

we already had a simlilar problem with öäü. I now know what the problem is and working on a solution for that.

**Comment by lukdiekm** [comment]
hi @antee please try release 0.3.2. it should work now.

**Comment by antee** [comment]
Thank you so much @lukdiekm! Works perfectly
