### ISSUE TITLE
Ampersands in Shortcut titles break list results

### ISSUE THREAD

**Issue by toph-allen** [lukdiekm/alfred-shortcuts#9]
Any shortcut with an ampersand in the title prevents Alfred from listing all shortcuts with this workflow. They probably need to be replaced with `&#38;`.

Minimal reproducible shortcut attached, but really, you just need to put an ampersand in the title of any shortcut.

[This & That.shortcut.zip](https://github.com/lukdiekm/alfred-shortcuts/files/8083293/This.That.shortcut.zip)

**Comment by lukdiekm** [comment]
hi @toph-allen, thanks for letting me know. this is fixed in the new release (0.3.3)
